# Travis configuration guide for R language:
#   https://docs.travis-ci.com/user/languages/r/
#   https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r

cache: packages

os:
  - linux

jobs:
  include:
  - r: devel
  - r: release
  - r: 3.5
  - r: 3.4

after_success:
  - Rscript -e 'covr::codecov()'
